id: I855E3E64
legacy_id: P006736
ocr_import_info:
  bdrc_scan_id: W1GS61550
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:58:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:24:28.853561+00:00'
last_modified: 2022-08-27 12:25:11.228506
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS61550
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS61550
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་ཐིག་ལེ་བཅུ་དྲུག་གི་ཟབ་ཁྲིད་མན་ངག་ཕྱོགས་བསྒྲིགས་དང་གསང་འདུས་འཇམ་དཔལ་རྡོ་རྗེའི་བསྐྱེད་རྫོགས།
  author: སྟག་ཚང་ལོ་ཙཱ་བ་ཤེས་རབ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.962641707849569
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1GS61552:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS61552
      total_pages: 341
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS61552.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.962641707849569
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
