id: opecha:P006736
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS61550
  title: བཀའ་གདམས་ཐིག་ལེ་བཅུ་དྲུག་གི་ཟབ་ཁྲིད་མན་ངག་ཕྱོགས་བསྒྲིགས་དང་གསང་འདུས་འཇམ་དཔལ་རྡོ་རྗེའི་བསྐྱེད་རྫོགས།
  volume: ''
  author: ''
