id: P006736
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS61550
  title: བཀའ་གདམས་ཐིག་ལེ་བཅུ་དྲུག་གི་ཟབ་ཁྲིད་མན་ངག་ཕྱོགས་བསྒྲིགས་དང་གསང་འདུས་འཇམ་དཔལ་རྡོ་རྗེའི་བསྐྱེད་རྫོགས།
  author: ''
  volumes:
    86509dced2ba4f86a64357452fe9d95e:
      image_group_id: I1GS61552
      title: ''
      volume_number: 1
      total_pages: 341
