id: P006736
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:08.728626
source_metadata:
  id: bdr:W1GS61550
  title: བཀའ་གདམས་ཐིག་ལེ་བཅུ་དྲུག་གི་ཟབ་ཁྲིད་མན་ངག་ཕྱོགས་བསྒྲིགས་དང་གསང་འདུས་འཇམ་དཔལ་རྡོ་རྗེའི་བསྐྱེད་རྫོགས།
  author: ''
  volumes:
    86509dced2ba4f86a64357452fe9d95e:
      image_group_id: I1GS61552
      title: ''
      volume_number: 1
      total_pages: 341
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
